name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.swift'
      - 'TimeRabbit.xcodeproj/**'
      - 'TimeRabbitTests/**'
      - '.github/workflows/ci.yml'
  push:
    branches: [ main ]
    paths:
      - '**.swift'
      - 'TimeRabbit.xcodeproj/**'
      - 'TimeRabbitTests/**'
      - '.github/workflows/ci.yml'

jobs:
  format-check:
    name: Check SwiftFormat
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Check SwiftFormat
        run: |
          echo "Checking SwiftFormat compliance..."
          swiftformat --lint . --exclude TimeRabbit.xcodeproj,build,.build
          if [ $? -ne 0 ]; then
            echo "❌ SwiftFormat check failed. Please run 'swiftformat .' locally and commit the changes."
            exit 1
          fi
          echo "✅ SwiftFormat check passed!"

  test:
    name: Run Tests
    runs-on: macos-15
    needs: format-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Run unit tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project TimeRabbit.xcodeproj \
            -scheme TimeRabbit \
            -destination 'platform=macOS' \
            -testPlan TimeRabbitTests \
            -enableCodeCoverage YES \
            | tee test-output.log

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output.log
          retention-days: 30

      - name: Check test results
        if: failure()
        run: |
          echo "Tests failed. Showing output:"
          cat test-output.log
