name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Run unit tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project TimeRabbit.xcodeproj \
            -scheme TimeRabbit \
            -destination 'platform=macOS' \
            -testPlan TimeRabbitTests \
            -enableCodeCoverage YES \
            | tee test-output.log

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output.log
          retention-days: 30

      - name: Check test results
        if: failure()
        run: |
          echo "Tests failed. Showing output:"
          cat test-output.log
